/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modules;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.*;
import java.util.regex.Pattern;

/**
 *
 * @author Sufyan
 */
public class AddDonorFrame extends javax.swing.JInternalFrame {

   
    Connection con;
    PreparedStatement pst;
    
    public AddDonorFrame() {
        initComponents();
        this.setBorder(null);
        BasicInternalFrameUI bui=(BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        autoID();

    }
    
    
    public void autoID()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/bloodbank","root","");
            
            Statement st= con.createStatement();
            
            ResultSet rs= st.executeQuery("SELECT Max(ID) FROM Donors");
            rs.next();
            
        
          
          if(rs.getString("Max(ID)")==null)
          {
              txtID.setText("10001");
          }
          else
          {
              Long id= Long.parseLong(rs.getString("Max(ID)"));
              id++;
              txtID.setText(String.format("%03d", id));
              
          }
            
            
            rs.close();
            st.close();
            con.close();
     
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    public void addDonor()
    {
        String name= txtName1.getText();
        String id= txtID.getText();
        String height= txtHeight.getText();
        String weight= txtWeight.getText();
        String address= txtAddress.getText();
        String phone= txtPhone.getText();
        String email= txtEmail1.getText();
        String user=txtAdmin.getText();

        if(name.equals("") || id.equals("") || height.equals("") || weight.equals("") || address.equals("") || phone.equals("") || email.equals("") || user.equals("") || txtGrpp.getSelectedItem().equals("--SELECT--") || txtAge.getSelectedItem().equals("--SELECT--") || txtGender.getSelectedItem().equals("--SELECT--")) 
        {
            JOptionPane.showMessageDialog(this, "ALL FIELDS ARE MANDATORY", "WARNING", JOptionPane.ERROR_MESSAGE);
        } 
        else if(txtPhone.getText().length()<=9)
        {
            JOptionPane.showMessageDialog(null, "ENTER VALID MOBILE NUMBER");
        }
        else
        {
            
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                con= DriverManager.getConnection("jdbc:mysql://localhost:3306/bloodbank","root","");
            
                String sql="INSERT INTO Donors (Bloodgrp,ID,Name,Age,Gender,Height,Weight,Address,Phone,Email,AddedBy) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
            
                pst=con.prepareStatement(sql);
            
                pst.setString(1, (String) txtGrpp.getSelectedItem());
                pst.setString(2, txtID.getText());
                pst.setString(3, txtName1.getText());
                pst.setString(4, (String) txtAge.getSelectedItem());
                pst.setString(5, (String) txtGender.getSelectedItem());
                pst.setString(6, txtHeight.getText());
                pst.setString(7, txtWeight.getText());
                pst.setString(8, txtAddress.getText());
                pst.setString(9, txtPhone.getText());
                pst.setString(10, txtEmail1.getText());
                pst.setString(11, txtAdmin.getText());
            
                pst.executeUpdate();
            
                JOptionPane.showMessageDialog(null, "DONOR ADDED SUCCESSFULLY");
            
          
                pst.close();
                con.close();
            
            
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
   
        }
                
    }                

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        txtGender = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        txtAge = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtGrpp = new javax.swing.JComboBox<>();
        kButton2 = new keeptoo.KButton();
        kButton3 = new keeptoo.KButton();
        txtHeight = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAdmin = new javax.swing.JTextField();
        txtName1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1485, 955));

        kGradientPanel2.setBackground(new java.awt.Color(153, 0, 51));
        kGradientPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 15), "ENTER DONOR DETAILS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 20), new java.awt.Color(255, 255, 255))); // NOI18N
        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkFillBackground(false);
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setLayout(null);

        txtGender.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT--", "MALE", "FEMALE", "OTHERS" }));
        txtGender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtGender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        kGradientPanel2.add(txtGender);
        txtGender.setBounds(210, 570, 220, 40);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("in Kgs");
        kGradientPanel2.add(jLabel1);
        jLabel1.setBounds(540, 790, 80, 33);

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DONOR ID :");
        kGradientPanel2.add(jLabel2);
        jLabel2.setBounds(40, 340, 150, 33);

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AGE :");
        kGradientPanel2.add(jLabel3);
        jLabel3.setBounds(90, 460, 80, 30);

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BLOOD GROUP :");
        kGradientPanel2.add(jLabel4);
        jLabel4.setBounds(480, 70, 200, 33);

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NAME :");
        kGradientPanel2.add(jLabel5);
        jLabel5.setBounds(70, 220, 110, 33);

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("GENDER :");
        kGradientPanel2.add(jLabel6);
        jLabel6.setBounds(60, 570, 120, 33);

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("WEIGHT :");
        kGradientPanel2.add(jLabel7);
        jLabel7.setBounds(60, 780, 120, 33);

        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ADDRESS :");
        kGradientPanel2.add(jLabel8);
        jLabel8.setBounds(810, 240, 130, 32);

        jLabel9.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("HEIGHT :");
        kGradientPanel2.add(jLabel9);
        jLabel9.setBounds(60, 680, 110, 33);

        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        txtID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        kGradientPanel2.add(txtID);
        txtID.setBounds(210, 340, 310, 40);

        jLabel10.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PHONE :");
        kGradientPanel2.add(jLabel10);
        jLabel10.setBounds(820, 430, 110, 33);

        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        txtAddress.setRows(5);
        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(txtAddress);

        kGradientPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(960, 210, 360, 141);

        txtAge.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT--", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75" }));
        txtAge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtAge.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        kGradientPanel2.add(txtAge);
        txtAge.setBounds(210, 460, 140, 40);

        jLabel11.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ADDED BY :");
        kGradientPanel2.add(jLabel11);
        jLabel11.setBounds(790, 650, 140, 33);

        jLabel12.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("in CM");
        kGradientPanel2.add(jLabel12);
        jLabel12.setBounds(540, 680, 70, 33);

        txtGrpp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtGrpp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT--", "A +", "A -", "B +", "B -", "AB +", "AB -", "O +", "O -" }));
        txtGrpp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtGrpp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtGrpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrppActionPerformed(evt);
            }
        });
        kGradientPanel2.add(txtGrpp);
        txtGrpp.setBounds(690, 70, 220, 40);

        kButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        kButton2.setText("CLEAR");
        kButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        kButton2.setkBorderRadius(0);
        kButton2.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton2.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton2.setkHoverColor(new java.awt.Color(0, 0, 0));
        kButton2.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton2.setkIndicatorColor(new java.awt.Color(0, 0, 0));
        kButton2.setkPressedColor(new java.awt.Color(255, 255, 255));
        kButton2.setkStartColor(new java.awt.Color(255, 255, 255));
        kButton2.setMaximumSize(new java.awt.Dimension(61, 40));
        kButton2.setMinimumSize(new java.awt.Dimension(61, 40));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(kButton2);
        kButton2.setBounds(880, 840, 130, 50);

        kButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        kButton3.setText("ADD");
        kButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        kButton3.setkBorderRadius(0);
        kButton3.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton3.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton3.setkHoverColor(new java.awt.Color(0, 0, 0));
        kButton3.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton3.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton3.setkIndicatorColor(new java.awt.Color(0, 0, 0));
        kButton3.setkPressedColor(new java.awt.Color(255, 255, 255));
        kButton3.setkStartColor(new java.awt.Color(255, 255, 255));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(kButton3);
        kButton3.setBounds(1090, 840, 130, 50);

        txtHeight.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        txtHeight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtHeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHeightKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHeightKeyTyped(evt);
            }
        });
        kGradientPanel2.add(txtHeight);
        txtHeight.setBounds(200, 680, 310, 40);

        txtWeight.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        txtWeight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtWeightKeyPressed(evt);
            }
        });
        kGradientPanel2.add(txtWeight);
        txtWeight.setBounds(200, 780, 310, 40);

        txtPhone.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        txtPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneKeyPressed(evt);
            }
        });
        kGradientPanel2.add(txtPhone);
        txtPhone.setBounds(960, 420, 310, 40);

        txtAdmin.setEditable(false);
        txtAdmin.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        txtAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        kGradientPanel2.add(txtAdmin);
        txtAdmin.setBounds(960, 650, 310, 40);

        txtName1.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        txtName1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtName1FocusGained(evt);
            }
        });
        kGradientPanel2.add(txtName1);
        txtName1.setBounds(210, 220, 310, 40);

        jLabel13.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("EMAIL :");
        kGradientPanel2.add(jLabel13);
        jLabel13.setBounds(820, 550, 110, 33);

        txtEmail1.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        txtEmail1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        kGradientPanel2.add(txtEmail1);
        txtEmail1.setBounds(960, 550, 310, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sufyan\\Downloads\\cassi-josh-lhnOvu72BM8-unsplash.jpg")); // NOI18N
        jLabel15.setText("jLabel15");
        kGradientPanel2.add(jLabel15);
        jLabel15.setBounds(10, 26, 1450, 880);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1469, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1469, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtGrppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrppActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed

        txtName1.setText("");
        txtID.setText("");
        txtHeight.setText("");
        txtWeight.setText("");
        txtAddress.setText("");
        txtPhone.setText("");
        txtAdmin.setText("");
        txtGrpp.setSelectedIndex(0);
        txtAge.setSelectedIndex(0);
        txtGender.setSelectedIndex(0);

    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
      
        addDonor();
        
    }//GEN-LAST:event_kButton3ActionPerformed

    private void txtName1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtName1FocusGained
    
    }//GEN-LAST:event_txtName1FocusGained

    private void txtHeightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHeightKeyPressed
        // TODO add your handling code here:
        String value = txtHeight.getText();
            int l = value.length();
            if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' ) {
               txtHeight.setEditable(true);
            //   label.setText("");
            } 
            else if(evt.getKeyCode()==KeyEvent.VK_BACK_SPACE)
            {
                
            }
            else {
               
               JOptionPane.showMessageDialog(null, "* Enter only numeric digits(0-9)");
               txtHeight.setText("");
            }
    }//GEN-LAST:event_txtHeightKeyPressed

    private void txtHeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHeightKeyTyped
        // TODO add your handling code here:

            
    }//GEN-LAST:event_txtHeightKeyTyped

    private void txtWeightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWeightKeyPressed
        // TODO add your handling code here:
        String value = txtWeight.getText();
            int l = value.length();
            if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' ) {
               
            //   label.setText("");
            } 
            
            else if(evt.getKeyCode()==KeyEvent.VK_BACK_SPACE)
            {
               
               
               txtWeight.setEditable(true);
               
            }
            else
            {
                JOptionPane.showMessageDialog(null, "* Enter only numeric digits(0-9)");
               txtWeight.setText("");
            }
    }//GEN-LAST:event_txtWeightKeyPressed

    private void txtPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyPressed
        
        String value=txtPhone.getText();
        int length=value.length();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if(length<10)
            {
                txtPhone.setEditable(true);
            }
            else
            {
                txtPhone.setEditable(false);
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE)
            {
                txtPhone.setEditable(true);
                
            }
            else
            {
                txtPhone.setEditable(false);
                
            }
        }
        
    }//GEN-LAST:event_txtPhoneKeyPressed

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KButton kButton2;
    private keeptoo.KButton kButton3;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JTextArea txtAddress;
    public javax.swing.JTextField txtAdmin;
    private javax.swing.JComboBox<String> txtAge;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JComboBox<String> txtGender;
    private javax.swing.JComboBox<String> txtGrpp;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}

  /*  String i=txtID.getText();
      
       if(Pattern.matches("[a-zA-Z]+",i))
       {
           JOptionPane.showMessageDialog(null,"Enter Numeric");
           txtID.setText("");
       }  */