/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modules;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sufyan
 */
public class Checkout extends javax.swing.JDialog {

    /**
     * Creates new form Checkout
     */
  
    
    
    public Checkout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billPanel = new javax.swing.JPanel();
        pnlprint = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblService = new javax.swing.JLabel();
        lblCompo = new javax.swing.JLabel();
        lblGrp = new javax.swing.JLabel();
        lblperUnit = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblTotal1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblDoc = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        billPanel.setBackground(new java.awt.Color(153, 153, 153));
        billPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        billPanel.setLayout(null);

        pnlprint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlprint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlprint.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 0, 2, 338));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlprint.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 2, 338));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlprint.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 0, 2, 338));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlprint.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 2, 338));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlprint.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1000, 2));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AMOUNT");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 0, 190, 40));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("COMPONENT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 160, 40));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BLOOD GROUP");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 160, 40));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("COST PER UNIT");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 170, 40));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("S.CHARGES");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 170, 40));

        pnlprint.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 1000, 40));

        lblService.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        lblService.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlprint.add(lblService, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 170, 40));

        lblCompo.setFont(new java.awt.Font("Arial", 1, 21)); // NOI18N
        lblCompo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlprint.add(lblCompo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 170, 50));

        lblGrp.setFont(new java.awt.Font("Arial", 1, 21)); // NOI18N
        lblGrp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlprint.add(lblGrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 130, 50));

        lblperUnit.setFont(new java.awt.Font("Arial", 1, 21)); // NOI18N
        lblperUnit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlprint.add(lblperUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 130, 50));

        lblAmount.setFont(new java.awt.Font("Arial", 1, 21)); // NOI18N
        lblAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlprint.add(lblAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, 130, 50));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("TOTAL :");
        pnlprint.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 100, 30));

        lblTotal1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblTotal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlprint.add(lblTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 270, 160, 40));

        billPanel.add(pnlprint);
        pnlprint.setBounds(70, 260, 1000, 340);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_drop_of_blood_80px.png"))); // NOI18N
        billPanel.add(jLabel7);
        jLabel7.setBounds(690, 40, 80, 90);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_drop_of_blood_80px.png"))); // NOI18N
        billPanel.add(jLabel8);
        jLabel8.setBounds(340, 40, 80, 90);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("BLOOD BANK");
        billPanel.add(jLabel9);
        jLabel9.setBounds(420, 40, 280, 60);

        lblType.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        billPanel.add(lblType);
        lblType.setBounds(750, 210, 210, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DATE :");
        billPanel.add(jLabel12);
        jLabel12.setBounds(690, 160, 60, 30);

        lblName.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        billPanel.add(lblName);
        lblName.setBounds(270, 130, 310, 30);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("DOB :");
        billPanel.add(jLabel15);
        jLabel15.setBounds(200, 170, 50, 30);

        lblDoc.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        billPanel.add(lblDoc);
        lblDoc.setBounds(260, 210, 270, 30);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("TYPE :");
        billPanel.add(jLabel17);
        jLabel17.setBounds(690, 210, 60, 30);

        lblDOB.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        billPanel.add(lblDOB);
        lblDOB.setBounds(260, 170, 270, 30);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("REFFERED BY :");
        billPanel.add(jLabel19);
        jLabel19.setBounds(120, 210, 130, 30);

        jLabel25.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("PATIENT NAME :");
        billPanel.add(jLabel25);
        jLabel25.setBounds(130, 130, 130, 30);

        lblDate.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        billPanel.add(lblDate);
        lblDate.setBounds(750, 160, 190, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sufyan\\Downloads\\cassi-josh-lhnOvu72BM8-unsplash.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        billPanel.add(jLabel4);
        jLabel4.setBounds(10, 10, 1110, 640);

        getContentPane().add(billPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 1130, 660));

        jButton1.setFont(new java.awt.Font("Verdana", 1, 21)); // NOI18N
        jButton1.setText("PRINT");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51), 4));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 714, 140, 40));

        jButton2.setFont(new java.awt.Font("Verdana", 1, 21)); // NOI18N
        jButton2.setText("CLOSE");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51), 4));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 714, 140, 40));

        setSize(new java.awt.Dimension(1231, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        PrinterJob printerjob= PrinterJob.getPrinterJob();
        printerjob.setJobName("Print Record");
        printerjob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
           
                if(pageIndex>0)
                {
                    return Printable.NO_SUCH_PAGE;
                    
                }
                
                Graphics2D graphics2d=(Graphics2D)graphics;
                graphics2d.translate(pageFormat.getImageableX()*2, pageFormat.getImageableY()*2);
                graphics2d.scale(0.5, 0.5);
                billPanel.paint(graphics2d);
                return Printable.PAGE_EXISTS;
                
            }
        });
        
        boolean returningResult=printerjob.printDialog();
        if(returningResult)
        {

            try {
                printerjob.print();
            } catch (PrinterException ex) {
                Logger.getLogger(Checkout.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Checkout dialog = new Checkout(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel billPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JLabel lblAmount;
    public javax.swing.JLabel lblCompo;
    public javax.swing.JLabel lblDOB;
    public javax.swing.JLabel lblDate;
    public javax.swing.JLabel lblDoc;
    public javax.swing.JLabel lblGrp;
    public javax.swing.JLabel lblName;
    public javax.swing.JLabel lblService;
    public javax.swing.JLabel lblTotal1;
    public javax.swing.JLabel lblType;
    public javax.swing.JLabel lblperUnit;
    private javax.swing.JPanel pnlprint;
    // End of variables declaration//GEN-END:variables
}
