/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modules;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sufyan
 */
@SuppressWarnings("serial")
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    
    int x,y;
    
    /**
     *
     */
     String user;
     public void addDonor()
     {
         AddDonorFrame adf= new AddDonorFrame();
        
        dp.add(adf);
        adf.setSize(dp.getWidth(), dp.getHeight());
	adf.setLocation(0,0);
        dp.moveToFront(adf);
        adf.setVisible(true);
        
        String u=lblAdmin.getText();
        adf.txtAdmin.setText(u);
        
        
        
     }
    
    public Dashboard() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(LogIn.class.getResource("/images/blood-drop.png")));
        
        exm();      
        

    }
    
    public void exm()
    {
        
        HomeFrame hf = new HomeFrame();
        dp.add(hf);
        hf.setVisible(true);     
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePane = new javax.swing.JPanel();
        button1 = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        btnPane1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        button2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnPane2 = new javax.swing.JPanel();
        button3 = new javax.swing.JPanel();
        btnPane3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        button4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnPane4 = new javax.swing.JPanel();
        button5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnPane5 = new javax.swing.JPanel();
        button6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnPane6 = new javax.swing.JPanel();
        button7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnPane7 = new javax.swing.JPanel();
        closePane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dragPane = new javax.swing.JPanel();
        lblLog = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        dp = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BBMS: DashBoard");
        setUndecorated(true);

        sidePane.setBackground(new java.awt.Color(0, 0, 0));
        sidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button1.setBackground(new java.awt.Color(0, 0, 0));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button1MousePressed(evt);
            }
        });
        button1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHome.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 255, 255));
        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_home_64px_1.png"))); // NOI18N
        lblHome.setText(" HOME");
        button1.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 240, 50));

        btnPane1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout btnPane1Layout = new javax.swing.GroupLayout(btnPane1);
        btnPane1.setLayout(btnPane1Layout);
        btnPane1Layout.setHorizontalGroup(
            btnPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        btnPane1Layout.setVerticalGroup(
            btnPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        button1.add(btnPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, -1));

        sidePane.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 370, 90));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_content_64px.png"))); // NOI18N
        jLabel2.setText("DASHBOARD");
        sidePane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 360, 66));

        button2.setBackground(new java.awt.Color(0, 0, 0));
        button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button2MousePressed(evt);
            }
        });
        button2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_add_new_60px.png"))); // NOI18N
        jLabel5.setText(" ADD DONOR");
        button2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 310, 50));

        btnPane2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout btnPane2Layout = new javax.swing.GroupLayout(btnPane2);
        btnPane2.setLayout(btnPane2Layout);
        btnPane2Layout.setHorizontalGroup(
            btnPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        btnPane2Layout.setVerticalGroup(
            btnPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        button2.add(btnPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, -1));

        sidePane.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 370, -1));

        button3.setBackground(new java.awt.Color(0, 0, 0));
        button3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button3MousePressed(evt);
            }
        });
        button3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPane3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout btnPane3Layout = new javax.swing.GroupLayout(btnPane3);
        btnPane3.setLayout(btnPane3Layout);
        btnPane3Layout.setHorizontalGroup(
            btnPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        btnPane3Layout.setVerticalGroup(
            btnPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        button3.add(btnPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 90));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_charity_60px_1.png"))); // NOI18N
        jLabel6.setText("  DONORS");
        button3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        sidePane.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 370, 90));

        button4.setBackground(new java.awt.Color(0, 0, 0));
        button4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button4MousePressed(evt);
            }
        });
        button4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_in_inventory_48px.png"))); // NOI18N
        jLabel7.setText("MANAGE BLOOD");
        button4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 330, 50));

        btnPane4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout btnPane4Layout = new javax.swing.GroupLayout(btnPane4);
        btnPane4.setLayout(btnPane4Layout);
        btnPane4Layout.setHorizontalGroup(
            btnPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        btnPane4Layout.setVerticalGroup(
            btnPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        button4.add(btnPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, -1));

        sidePane.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 370, -1));

        button5.setBackground(new java.awt.Color(0, 0, 0));
        button5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button5MousePressed(evt);
            }
        });
        button5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_sell_60px_1.png"))); // NOI18N
        jLabel8.setText(" SELL");
        button5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 250, 50));

        btnPane5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout btnPane5Layout = new javax.swing.GroupLayout(btnPane5);
        btnPane5.setLayout(btnPane5Layout);
        btnPane5Layout.setHorizontalGroup(
            btnPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        btnPane5Layout.setVerticalGroup(
            btnPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        button5.add(btnPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, -1));

        sidePane.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 370, 90));

        button6.setBackground(new java.awt.Color(0, 0, 0));
        button6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button6MousePressed(evt);
            }
        });
        button6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_automation_60px.png"))); // NOI18N
        jLabel9.setText("CONFIGURATION");
        button6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 330, 60));

        btnPane6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout btnPane6Layout = new javax.swing.GroupLayout(btnPane6);
        btnPane6.setLayout(btnPane6Layout);
        btnPane6Layout.setHorizontalGroup(
            btnPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        btnPane6Layout.setVerticalGroup(
            btnPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        button6.add(btnPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, -1));

        sidePane.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 810, 370, 90));

        button7.setBackground(new java.awt.Color(0, 0, 0));
        button7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button7MousePressed(evt);
            }
        });
        button7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_moleskine_64px.png"))); // NOI18N
        jLabel10.setText(" RECORDS");
        button7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 280, 60));

        btnPane7.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout btnPane7Layout = new javax.swing.GroupLayout(btnPane7);
        btnPane7.setLayout(btnPane7Layout);
        btnPane7Layout.setHorizontalGroup(
            btnPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        btnPane7Layout.setVerticalGroup(
            btnPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        button7.add(btnPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, -1));

        sidePane.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 370, 90));

        closePane.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-");
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 27)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setToolTipText("");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout closePaneLayout = new javax.swing.GroupLayout(closePane);
        closePane.setLayout(closePaneLayout);
        closePaneLayout.setHorizontalGroup(
            closePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        closePaneLayout.setVerticalGroup(
            closePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closePaneLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1))
            .addComponent(jLabel3)
        );

        dragPane.setBackground(new java.awt.Color(0, 0, 0));
        dragPane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dragPane.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragPaneMouseDragged(evt);
            }
        });
        dragPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragPaneMousePressed(evt);
            }
        });
        dragPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLog.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblLog.setForeground(new java.awt.Color(255, 255, 255));
        lblLog.setText("LOGGED BY:");
        dragPane.add(lblLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 134, 43));

        lblAdmin.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(255, 255, 255));
        dragPane.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 0, 210, 43));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("LOG OUT");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        dragPane.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 130, 40));

        dp.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dpLayout = new javax.swing.GroupLayout(dp);
        dp.setLayout(dpLayout);
        dpLayout.setHorizontalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1485, Short.MAX_VALUE)
        );
        dpLayout.setVerticalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePane, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dragPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(closePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dp)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePane, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dragPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(closePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(dp))
        );

        setSize(new java.awt.Dimension(1855, 998));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(Dashboard.ICONIFIED);
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void dragPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragPaneMousePressed
        
        x=evt.getX();
        y=evt.getY();
        
    }//GEN-LAST:event_dragPaneMousePressed

    private void dragPaneMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragPaneMouseDragged
       
        int xx=evt.getXOnScreen();
        int yy=evt.getYOnScreen();
        setLocation(xx-x,yy-y);
        
    }//GEN-LAST:event_dragPaneMouseDragged

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
       
       
 
    }//GEN-LAST:event_jLabel3MouseClicked

    private void button2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MousePressed
       
        resetColor(button1, btnPane1);
        setColor(button2,btnPane2);
        resetColor(button3, btnPane3);
        resetColor(button4, btnPane4);
        resetColor(button5, btnPane5);
        resetColor(button6, btnPane6);
        resetColor(button7, btnPane7);
   
    }//GEN-LAST:event_button2MousePressed

    private void button1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MousePressed
        
        setColor(button1, btnPane1);
        resetColor(button2,btnPane2);
        resetColor(button3, btnPane3);
        resetColor(button4, btnPane4);
        resetColor(button5, btnPane5);
        resetColor(button6, btnPane6);
        resetColor(button7, btnPane7);
  
    }//GEN-LAST:event_button1MousePressed

    private void button3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button3MousePressed
        
        resetColor(button1, btnPane1);
        resetColor(button2,btnPane2);
        setColor(button3, btnPane3);
        resetColor(button4, btnPane4);
        resetColor(button5, btnPane5);
        resetColor(button6, btnPane6);
        resetColor(button7, btnPane7);
   
    }//GEN-LAST:event_button3MousePressed

    private void button4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MousePressed
    
        resetColor(button1, btnPane1);
        resetColor(button2,btnPane2);
        resetColor(button3, btnPane3);
        setColor(button4, btnPane4);
        resetColor(button5, btnPane5);
        resetColor(button6, btnPane6);
        resetColor(button7, btnPane7);
        
    }//GEN-LAST:event_button4MousePressed

    private void button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseClicked
      
        AddDonorFrame adf= new AddDonorFrame();
        
        dp.add(adf);
        adf.setSize(dp.getWidth(), dp.getHeight());
	adf.setLocation(0,0);
        dp.moveToFront(adf);
        adf.setVisible(true);
        
        String u=lblAdmin.getText();
        adf.txtAdmin.setText(u);
        
  
    }//GEN-LAST:event_button2MouseClicked

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
      
        HomeFrame hf1= new HomeFrame();
        
        dp.add(hf1);
        hf1.setSize(dp.getWidth(), dp.getHeight());
	hf1.setLocation(0,0);
        dp.moveToFront(hf1);
        hf1.setVisible(true);
        
    }//GEN-LAST:event_button1MouseClicked

    private void button3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button3MouseClicked
       
        DonorList dl= new DonorList();
        
        dp.add(dl);
        dl.setSize(dp.getWidth(), dp.getHeight());
	dl.setLocation(0,0);
        dp.moveToFront(dl);
        dl.setVisible(true);
        
        
        
    }//GEN-LAST:event_button3MouseClicked

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed

         int x=JOptionPane.showConfirmDialog(this, "WOULD YOU LIKE TO EXIT", "CONFIRM", JOptionPane.YES_NO_OPTION);
        if(x==0)
        {
            System.exit(0);
        }
  
        
    }//GEN-LAST:event_jLabel3MousePressed

    private void button4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MouseClicked
       
        AddBlood ab=new AddBlood();
        dp.add(ab);
        ab.setSize(dp.getWidth(), dp.getHeight());
	ab.setLocation(0,0);
        dp.moveToFront(ab);
        ab.setVisible(true);
    }//GEN-LAST:event_button4MouseClicked

    private void button5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MousePressed
      
        resetColor(button1, btnPane1);
        resetColor(button2,btnPane2);
        resetColor(button3, btnPane3);
        resetColor(button4, btnPane4);
        setColor(button5, btnPane5);
        resetColor(button6, btnPane6);
        resetColor(button7, btnPane7);
 
    }//GEN-LAST:event_button5MousePressed

    private void button6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button6MousePressed
        
        resetColor(button1, btnPane1);
        resetColor(button2,btnPane2);
        resetColor(button3, btnPane3);
        resetColor(button4, btnPane4);
        resetColor(button5, btnPane5);
        setColor(button6, btnPane6);
        resetColor(button7, btnPane7);
        
    }//GEN-LAST:event_button6MousePressed

    private void button6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button6MouseClicked
      
        Config c=new Config();
        dp.add(c);
        c.setSize(dp.getWidth(), dp.getHeight());
	c.setLocation(0,0);
        dp.moveToFront(c);
        c.setVisible(true);
        
        String u=lblAdmin.getText();
        c.txtAdmin.setText(u);
        c.txtAdmin1.setText(u);
        
    }//GEN-LAST:event_button6MouseClicked

    private void button5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MouseClicked
        
        Sell s=new Sell();
        dp.add(s);
        s.setSize(dp.getWidth(), dp.getHeight());
	s.setLocation(0,0);
        dp.moveToFront(s);
        s.setVisible(true);
        s.txtAdminName.setText(lblAdmin.getText());
        
    }//GEN-LAST:event_button5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        LogIn l=new LogIn();
        this.dispose();
        l.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button7MouseClicked

        Records r=new Records();
        dp.add(r);
        r.setSize(dp.getWidth(), dp.getHeight());
	r.setLocation(0,0);
        dp.moveToFront(r);
        r.setVisible(true);
        
    }//GEN-LAST:event_button7MouseClicked

    private void button7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button7MousePressed

        resetColor(button1, btnPane1);
        resetColor(button2,btnPane2);
        resetColor(button3, btnPane3);
        resetColor(button4, btnPane4);
        resetColor(button5, btnPane5);
        resetColor(button6, btnPane6);
        setColor(button7, btnPane7);
    }//GEN-LAST:event_button7MousePressed

    private void button2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button2MouseEntered

    
   public void setColor(JPanel panel1,JPanel panel2)
   {
       panel1.setBackground(new java.awt.Color(51, 51, 51));
       panel2.setBackground(new java.awt.Color(255, 255, 255));
       
   }
   
   public void resetColor(JPanel panel1,JPanel panel2)
   {
        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel2.setBackground(new java.awt.Color(0, 0, 0));
   }
   
    
     
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnPane1;
    public javax.swing.JPanel btnPane2;
    public javax.swing.JPanel btnPane3;
    public javax.swing.JPanel btnPane4;
    public javax.swing.JPanel btnPane5;
    public javax.swing.JPanel btnPane6;
    public javax.swing.JPanel btnPane7;
    public javax.swing.JPanel button1;
    public javax.swing.JPanel button2;
    public javax.swing.JPanel button3;
    public javax.swing.JPanel button4;
    public javax.swing.JPanel button5;
    public javax.swing.JPanel button6;
    public javax.swing.JPanel button7;
    private javax.swing.JPanel closePane;
    public javax.swing.JDesktopPane dp;
    private javax.swing.JPanel dragPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblLog;
    private javax.swing.JPanel sidePane;
    // End of variables declaration//GEN-END:variables

    
         
    


}
