/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modules;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Sufyan
 */
public class HomeFrame extends javax.swing.JInternalFrame {

  

    /**
     * Creates new form HomeFrame
     * @param b
     */
    
    public void expiry()
    {
        String sql=null;
        try
        {
            for(int i=1;i<=3;i++)
            {
                switch (i) {
                    case 1:
                        sql="Select count(*) as Expiry FROM WholeBlood where `Expiry Date`<CURDATE() and status='ACTIVE'";
                        break;
                    case 2:
                        sql="Select count(*) as Expiry FROM rbc where `Expiry Date`<CURDATE() and status='ACTIVE'";
                        break;
                    case 3:
                        sql="Select count(*) as Expiry FROM plasma where `Expiry Date`<CURDATE() and status='ACTIVE'";
                        break;    
                    default:
                        break;
                }
                
                Class.forName("com.mysql.jdbc.Driver");
                Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/bloodbank","root","");
                
                PreparedStatement pst=con.prepareStatement(sql);
                ResultSet rs=pst.executeQuery();
                while(rs.next())
                {
                    int count=rs.getInt("Expiry");
                    if(count>0)
                    {
                        lblExpiry.setText("EXPIRED BLOOD BAGS");
                        btnExpiry.setEnabled(true);
                    }
                }
                
                
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    
    public String getCount(String b,String c)
    {
       String blood=b;
       String compo=c;
       String count=null;
       try
       {
           Class.forName("com.mysql.jdbc.Driver");
           Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/bloodbank","root","");
           
           String sql="SELECT COUNT(*) AS Count from "+compo+" WHERE `Blood Group`='"+blood+"' and Status='ACTIVE'  and CURDATE()<`Expiry Date` ";
           
           PreparedStatement pst=con.prepareStatement(sql);
           ResultSet rs=pst.executeQuery();
           
           while(rs.next())
           {
               count=rs.getString("count");
               
           }
           rs.close();
           pst.close();
           con.close();
    
       }
       catch(Exception e)
       {
           System.out.println(e);
       }
        return(count);
       
    }
    
    
    public HomeFrame() {
        initComponents();
        
        this.setBorder(null);
        BasicInternalFrameUI bui=(BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        apwb.setText(getCount("A +", "WholeBlood"));
        aprbc.setText(getCount("A +", "RBC"));
        applsma.setText(getCount("A +", "PLASMA"));
        
        anwb.setText(getCount("A -", "WholeBlood"));
        anrbc.setText(getCount("A -", "RBC"));
        anplsma.setText(getCount("A -", "PLASMA"));
        
        bpwb.setText(getCount("B +", "WholeBlood"));
        bprbc.setText(getCount("B +", "RBC"));
        bpplsma.setText(getCount("B +", "PLASMA"));
        
        bnwb.setText(getCount("B -", "WholeBlood"));
        bnrbc.setText(getCount("B -", "RBC"));
        bnplsma.setText(getCount("B -", "PLASMA"));
        
        opwb.setText(getCount("O +", "WholeBlood"));
        oprbc.setText(getCount("O +", "RBC"));
        opplsma.setText(getCount("O +", "PLASMA"));
        
        onwb.setText(getCount("O -", "WholeBlood"));
        onrbc.setText(getCount("O -", "RBC"));
        onplsma.setText(getCount("O -", "PLASMA"));
        
        abpwb.setText(getCount("AB +", "WholeBlood"));
        abprbc.setText(getCount("AB +", "RBC"));
        abpplsma.setText(getCount("AB +", "PLASMA"));
        
        abnwb.setText(getCount("AB -", "WholeBlood"));
        abnrbc.setText(getCount("AB -", "RBC"));
        abnplsma.setText(getCount("AB -", "PLASMA"));
        
        
        expiry();
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        applsma = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        apwb = new javax.swing.JLabel();
        aprbc = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        anwb = new javax.swing.JLabel();
        anrbc = new javax.swing.JLabel();
        anplsma = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bpwb = new javax.swing.JLabel();
        bprbc = new javax.swing.JLabel();
        bpplsma = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        opwb = new javax.swing.JLabel();
        oprbc = new javax.swing.JLabel();
        opplsma = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bnwb = new javax.swing.JLabel();
        bnrbc = new javax.swing.JLabel();
        bnplsma = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        onwb = new javax.swing.JLabel();
        onrbc = new javax.swing.JLabel();
        onplsma = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        abpwb = new javax.swing.JLabel();
        abprbc = new javax.swing.JLabel();
        abpplsma = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        abnwb = new javax.swing.JLabel();
        abnrbc = new javax.swing.JLabel();
        abnplsma = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        lblExpiry = new javax.swing.JLabel();
        btnExpiry = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        kGradientPanel1.setBackground(new java.awt.Color(153, 153, 153));
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(51, 51, 51));
        kGradientPanel1.setkFillBackground(false);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 51, 51));
        kGradientPanel1.setkTransparentControls(false);
        kGradientPanel1.setLayout(null);

        kGradientPanel3.setBackground(new java.awt.Color(204, 0, 0));
        kGradientPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 8), "STATUS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 22), new java.awt.Color(255, 255, 255))); // NOI18N
        kGradientPanel3.setForeground(new java.awt.Color(153, 255, 153));
        kGradientPanel3.setFocusable(false);
        kGradientPanel3.setkBorderRadius(0);
        kGradientPanel3.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel3.setkFillBackground(false);
        kGradientPanel3.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel3.setkTransparentControls(false);
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "A+ BLOOD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 17))); // NOI18N

        applsma.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        applsma.setForeground(new java.awt.Color(0, 0, 153));
        applsma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        applsma.setText("1");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setText("WHOLE BLOOD :");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel4.setText("PLASMA :");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel5.setText("RBC :");

        apwb.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        apwb.setForeground(new java.awt.Color(0, 0, 153));
        apwb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apwb.setText("1");

        aprbc.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        aprbc.setForeground(new java.awt.Color(0, 0, 153));
        aprbc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aprbc.setText("1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(apwb, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aprbc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(applsma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apwb, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aprbc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applsma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        kGradientPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 88, 273, 156));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "A- BLOOD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 17))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel8.setText("RBC :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 68, -1, 31));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel9.setText("WHOLE BLOOD :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, -1, 31));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel10.setText("PLASMA :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 104, -1, 31));

        anwb.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        anwb.setForeground(new java.awt.Color(0, 0, 153));
        anwb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anwb.setText("1");
        jPanel3.add(anwb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 60, 30));

        anrbc.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        anrbc.setForeground(new java.awt.Color(0, 0, 153));
        anrbc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anrbc.setText("1");
        jPanel3.add(anrbc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 60, 30));

        anplsma.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        anplsma.setForeground(new java.awt.Color(0, 0, 153));
        anplsma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anplsma.setText("1");
        jPanel3.add(anplsma, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 60, 30));

        kGradientPanel3.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 273, 156));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "B+ BLOOD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 17))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel11.setText("RBC :");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 68, -1, 31));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel12.setText("WHOLE BLOOD :");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, -1, 31));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel13.setText("PLASMA :");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 104, -1, 31));

        bpwb.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        bpwb.setForeground(new java.awt.Color(0, 0, 153));
        bpwb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bpwb.setText("1");
        jPanel4.add(bpwb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 60, 30));

        bprbc.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        bprbc.setForeground(new java.awt.Color(0, 0, 153));
        bprbc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bprbc.setText("1");
        jPanel4.add(bprbc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 60, 30));

        bpplsma.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        bpplsma.setForeground(new java.awt.Color(0, 0, 153));
        bpplsma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bpplsma.setText("1");
        jPanel4.add(bpplsma, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 60, 30));

        kGradientPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 273, 156));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "O+ BLOOD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 17))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel17.setText("RBC :");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 68, -1, 31));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel18.setText("WHOLE BLOOD :");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, -1, 31));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel19.setText("PLASMA :");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 104, -1, 31));

        opwb.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        opwb.setForeground(new java.awt.Color(0, 0, 153));
        opwb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        opwb.setText("1");
        jPanel6.add(opwb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 60, 30));

        oprbc.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        oprbc.setForeground(new java.awt.Color(0, 0, 153));
        oprbc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oprbc.setText("1");
        jPanel6.add(oprbc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 60, 30));

        opplsma.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        opplsma.setForeground(new java.awt.Color(0, 0, 153));
        opplsma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        opplsma.setText("1");
        jPanel6.add(opplsma, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 60, 30));

        kGradientPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 273, 156));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "B- BLOOD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 17))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel14.setText("RBC :");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 68, -1, 31));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel15.setText("WHOLE BLOOD :");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, -1, 31));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel16.setText("PLASMA :");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 104, -1, 31));

        bnwb.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        bnwb.setForeground(new java.awt.Color(0, 0, 153));
        bnwb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bnwb.setText("1");
        jPanel5.add(bnwb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 60, 30));

        bnrbc.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        bnrbc.setForeground(new java.awt.Color(0, 0, 153));
        bnrbc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bnrbc.setText("1");
        jPanel5.add(bnrbc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 60, 30));

        bnplsma.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        bnplsma.setForeground(new java.awt.Color(0, 0, 153));
        bnplsma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bnplsma.setText("1");
        jPanel5.add(bnplsma, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 60, 30));

        kGradientPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 273, 156));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "O- BLOOD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 17))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel20.setText("RBC :");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 68, -1, 31));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel21.setText("WHOLE BLOOD :");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, -1, 31));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel22.setText("PLASMA :");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 104, -1, 31));

        onwb.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        onwb.setForeground(new java.awt.Color(0, 0, 153));
        onwb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        onwb.setText("1");
        jPanel7.add(onwb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 60, 30));

        onrbc.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        onrbc.setForeground(new java.awt.Color(0, 0, 153));
        onrbc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        onrbc.setText("1");
        jPanel7.add(onrbc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 60, 30));

        onplsma.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        onplsma.setForeground(new java.awt.Color(0, 0, 153));
        onplsma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        onplsma.setText("1");
        jPanel7.add(onplsma, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 60, 30));

        kGradientPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 273, 156));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "AB+ BLOOD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 17))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel23.setText("RBC :");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 68, -1, 31));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel24.setText("WHOLE BLOOD :");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, -1, 31));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel25.setText("PLASMA :");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 104, -1, 31));

        abpwb.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        abpwb.setForeground(new java.awt.Color(0, 0, 153));
        abpwb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abpwb.setText("1");
        jPanel8.add(abpwb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 60, 30));

        abprbc.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        abprbc.setForeground(new java.awt.Color(0, 0, 153));
        abprbc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abprbc.setText("1");
        jPanel8.add(abprbc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 60, 30));

        abpplsma.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        abpplsma.setForeground(new java.awt.Color(0, 0, 153));
        abpplsma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abpplsma.setText("1");
        jPanel8.add(abpplsma, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 60, 30));

        kGradientPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 273, 156));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "AB- BLOOD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 17))); // NOI18N
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel26.setText("RBC :");
        jPanel9.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 68, -1, 31));

        jLabel27.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel27.setText("WHOLE BLOOD :");
        jPanel9.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, -1, 31));

        jLabel28.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel28.setText("PLASMA :");
        jPanel9.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 104, -1, 31));

        abnwb.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        abnwb.setForeground(new java.awt.Color(0, 0, 153));
        abnwb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abnwb.setText("1");
        jPanel9.add(abnwb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 60, 30));

        abnrbc.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        abnrbc.setForeground(new java.awt.Color(0, 0, 153));
        abnrbc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abnrbc.setText("1");
        jPanel9.add(abnrbc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 60, 30));

        abnplsma.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        abnplsma.setForeground(new java.awt.Color(0, 0, 153));
        abnplsma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abnplsma.setText("1");
        jPanel9.add(abnplsma, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 60, 30));

        kGradientPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 273, 156));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sufyan\\Downloads\\cassi-josh-lhnOvu72BM8-unsplash.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        kGradientPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 970, 680));

        kGradientPanel1.add(kGradientPanel3);
        kGradientPanel3.setBounds(10, 210, 990, 720);

        kGradientPanel2.setBackground(new java.awt.Color(204, 0, 51));
        kGradientPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5), "NOTIFICATION", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        kGradientPanel2.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel2.setkFillBackground(false);
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel2.setkTransparentControls(false);
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExpiry.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblExpiry.setForeground(new java.awt.Color(255, 255, 255));
        lblExpiry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExpiry.setText("THERE ARE NO EXPIRED BLOOD BAGS PRESENT");
        lblExpiry.setToolTipText("");
        kGradientPanel2.add(lblExpiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 452, 39));

        btnExpiry.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        btnExpiry.setText("CLICK HERE TO VIEW");
        btnExpiry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnExpiry.setEnabled(false);
        btnExpiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpiryActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnExpiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 214, 37));

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sufyan\\Downloads\\cassi-josh-lhnOvu72BM8-unsplash.jpg")); // NOI18N
        jLabel29.setText("jLabel29");
        jLabel29.setPreferredSize(new java.awt.Dimension(320, 200));
        kGradientPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 450, 240));

        kGradientPanel1.add(kGradientPanel2);
        kGradientPanel2.setBounds(1010, 210, 470, 280);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMINISTRATOR");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 8));
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(380, 30, 710, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sufyan\\Downloads\\cassi-josh-lhnOvu72BM8-unsplash.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(0, -51, 1480, 1900);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1485, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExpiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpiryActionPerformed
       
        Expired e=new Expired(null, true);
        e.show();
        
    }//GEN-LAST:event_btnExpiryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abnplsma;
    private javax.swing.JLabel abnrbc;
    private javax.swing.JLabel abnwb;
    private javax.swing.JLabel abpplsma;
    private javax.swing.JLabel abprbc;
    private javax.swing.JLabel abpwb;
    private javax.swing.JLabel anplsma;
    private javax.swing.JLabel anrbc;
    private javax.swing.JLabel anwb;
    private javax.swing.JLabel applsma;
    private javax.swing.JLabel aprbc;
    private javax.swing.JLabel apwb;
    private javax.swing.JLabel bnplsma;
    private javax.swing.JLabel bnrbc;
    private javax.swing.JLabel bnwb;
    private javax.swing.JLabel bpplsma;
    private javax.swing.JLabel bprbc;
    private javax.swing.JLabel bpwb;
    private javax.swing.JButton btnExpiry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JLabel lblExpiry;
    private javax.swing.JLabel onplsma;
    private javax.swing.JLabel onrbc;
    private javax.swing.JLabel onwb;
    private javax.swing.JLabel opplsma;
    private javax.swing.JLabel oprbc;
    private javax.swing.JLabel opwb;
    // End of variables declaration//GEN-END:variables
}
